volumes:
  datamachine-logs:
  grafana-storage:
secrets:
  grafana_admin_password:
    file: ./.local/grafana_admin_password
services:
  collector:
    container_name: collector
    image: alpine:latest
    environment:
      - LOG_DIR=/var/log/datamachine
      - COLLECTOR_ADDR=0.0.0.0
      - COLLECTOR_PORT=8080
      - GENERATOR_ADDR=generator
      - GENERATOR_PORT=8081
      - HEALTHCHECK_PORT=80
    entrypoint: /opt/collector
    volumes:
      - ./datamachine/build/bin/collector:/opt/collector
      - datamachine-logs:/var/log/datamachine
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/healthcheck"]
      interval: 5s
      timeout: 3s
      retries: 3
  generator:
    container_name: generator
    image: alpine:latest
    environment:
      - LOG_DIR=/var/log/datamachine
      - COLLECTOR_ADDR=collector
      - COLLECTOR_PORT=8080
      - GENERATOR_ADDR=0.0.0.0
      - GENERATOR_PORT=8081
      - HEALTHCHECK_PORT=80
    entrypoint: /opt/generator
    volumes:
      - ./datamachine/build/bin/generator:/opt/generator
      - datamachine-logs:/var/log/datamachine
    depends_on:
      collector:
        condition: service_healthy
  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    secrets:
      - grafana_admin_password
    environment:
      - GF_LOG_LEVEL=info
      - GF_PLUGINS_PREINSTALL=grafana-clock-panel, grafana-simple-json-datasource
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana_admin_password
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000
